config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: [:destroy]
  resources :words, only: :index
  resources :categories, only: [:index, :show] do
    resources :lessons
  end
  resources :lessons
  resources :relationships, only: [:index, :create, :destroy]
  namespace :admin do
    root "dashboard#index", as: :home
    resources :categories
    resources :words
    resources :users, only: [:index, :destroy]
  end
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy

  belongs_to :category

  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: lambda {|attributes| attributes[:content].blank?}

  validates :content, presence: true
  validate :valid_answer_numbers
  validate :check_correct_answer

  scope :sort, -> {order created_at: :desc}
  scope :order_by_content, -> {order :content}
  scope :find_all, -> {joins(:answers).where("is_correct = ?", true).
    select("words.content as word_content, answers.content as answer_content")}
  scope :search_words, -> value {joins(:answers).
    where("words.content LIKE ? AND is_correct = ?", "%#{value}%", true).
    select("words.content as word_content, answers.content as answer_content")}

  scope :filter_by_category, -> category_id {where "category_id = ?",
    category_id if category_id.present?}
  scope :all_words, -> user_id{}
  scope :learned, -> user_id {where "words.id in (SELECT r. word_id
    FROM lessons l join results r
    on l.id = r.lesson_id join answers a on r.word_id = a.word_id
    where l.user_id = ? AND a.is_correct = ?)", user_id, true}
  scope :not_learned, ->  user_id {where "words.id not in (SELECT r. word_id
    FROM lessons l join results r
    on l.id = r.lesson_id join answers a on r.word_id = a.word_id
    where l.user_id = ? AND a.is_correct = ?)", user_id, true}

  class << self
    def search value
      if value.present?
        search_words value
      else
        find_all
      end
    end
  end

  private
  def valid_answer_numbers
    errors.add :answer, I18n.t("models.word.num_answers") if answers.size < 2
  end

  def check_correct_answer
    correct_answer = answers.select {|answers| answers.is_correct?}
    errors.add :correct_answer,
      I18n.t("models.word.need_avaliable") if correct_answer.empty?
    errors.add :correct_answer,
      I18n.t("models.word.no_more_than_one") if correct_answer.size > 1
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :load_words
  before_action :find_word, except: [:index, :create, :new]
  include CategoryUtils

  def index
  end

  def new
    @word = Word.new
      Settings.answers_num_default.times{@word.answers.build}
  end

  def create
    @word = Word.new word_params
    @word.save
    respond_to do |format|
      format.js
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t "controllers.admin.update_success"
      redirect_to new_admin_word_path
    else
      render :edit
    end
  end

  def destroy
    @word.destroy
    respond_to do |format|
      format.js
    end
  end

  private
  def word_params
    params.require(:word).permit :content, :category_id,
      answers_attributes: [:content, :is_correct, :_destroy, :id]
  end

  def load_words
    @words = Word.sort.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def find_word
    @word = Word.find_by id: params[:id]
    if @word.nil?
      flash[:danger] = t "flash.error"
      redirect_to new_admin_word_path
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user, only: :index

  include CategoryUtils

  def index
    @words = if params[:option].present?
      Word.filter_by_category(params[:category_id])
        .send(params[:option], current_user)
    else
      Word.all
    end.order_by_content
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/views/admin/words/_answer_field.html.erb
<fieldset class="col-md-12 fields">
  <div class="col-md-2">
    <%= f.check_box :is_correct, class: "check_answers", value: false %>
  </div>
  <div class="col-md-8"><%= f.text_field :content %></div>
  <%= f.hidden_field :_destroy %>
  <div class="col-md-2">
    <%= link_to "remove", "#", class: "btn btn-danger remove-fields" %>
  </div>
</fieldset>

app/views/admin/words/_form.html.erb
<div class="container-fluid main-container">
  <%= render "layouts/admin/admin_navbar" %>
  <div class="col-md-9 content">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= t ".word" %>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-2" id="height-600">
          <h2><%= t ".add_new_word" %></h2>
          <%= form_for [:admin, @word], remote: true do |f| %>
            <div id="div-error-messages" ></div>
            <%= f.text_field :content, placeholder: t(".place_word") %></br>
            <%= f.select :category_id, @categories %>
            <div class="row-answer">
              <%= f.fields_for :answers do |answer| %>
                <%= render "answer_field", f: answer %>
              <% end %>
              <%= link_to_add_fields t(".add_answer"), f, :answers %>
            </div>
            <%= f.submit yield(:button_text), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
      <div id="div-words">
        <%= render @words %>
        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>

app/views/admin/words/_word.html.erb
<ul class="list-group product-word-all" id="word-item-<%= word.id %>">
  <li class="list-group-item">
    <%= word.content %>
    <%= link_to t("delete"),[:admin, word], remote: true,
      method: :delete, data: {confirm: t("delete_success")}, id: "delete-word"%>
    <%= link_to t("edit"), edit_admin_word_path(word.id),
      id: "edit-word"  %>
  </li>
</ul>

app/views/admin/words/create.js.erb
<% if @word.errors.any? %>
  $("#div-error-messages").html(
    "<%= j render("shared/error_messages", object: @word) %>");
<% else %>
  $('#div-words').prepend("<%= j render @word %>");
<% end %>

app/views/admin/words/destroy.js.erb
$('#word-item-<%= @word.id %>').remove();

app/views/admin/words/edit.html.erb
<% provide :button_text, t("edit") %>
<%= render "form" %>

app/views/admin/words/new.html.erb
<% provide :button_text, t("add") %>
<%= render "form" %>