config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: [:destroy]
  resources :words, only: :index
  resources :categories, only: [:index, :show] do
    resources :lessons
  end
  resources :lessons
  resources :relationships, only: [:index, :create, :destroy]
  namespace :admin do
    root "dashboard#index", as: :home
    resources :categories
    resources :words
    resources :users, only: [:index, :destroy]
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "flash.formcontains" %> <%= pluralize object.errors.count,
        t("flash.error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <div class="div-following">
    <%= link_to relationships_path id: @user.id, title: "following" do %>
      <strong id="following" class="stat">
        <%= @user.following.count %>
      </strong>
      <p><%= t ".following" %></p>
    <% end %>
  </div>
  <div class="div-followers">
    <%= link_to relationships_path id: @user.id, title: "followers" do %>
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
      <p><%= t ".follower" %></p>
    <% end %>
  </div>
</div>