config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: [:destroy]
  resources :words, only: :index
  resources :categories, only: [:index, :show] do
    resources :lessons
  end
  resources :lessons
  resources :relationships, only: [:index, :create, :destroy]
  namespace :admin do
    root "dashboard#index", as: :home
    resources :categories
    resources :words
    resources :users, only: [:index, :destroy]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy

  validates :name, presence: true, length: {maximum: 20}
  validates :duration, presence: true,
    numericality: {greater_than_or_equal_to: 0, only_integer: true}
  validates :word_per_lesson, presence: true,
    numericality: {greater_than_or_equal_to: 0, only_integer: true}

  scope :sort, -> {order created_at: :desc}
  scope :search_categories, -> search {where "name LIKE ?",
    "%#{search}%"}

  class << self
    def search search
      if search
        search_categories search
      else
        Category.all
      end
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :find_category, only: [:update, :edit, :destroy]
  before_action :load_categories, only: [:edit, :update, :new]

  def index
    @categories = Category.search(params[:search]).paginate page:
      params[:page], per_page: Settings.per_page
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      respond_to do |format|
        format.js
      end
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "controllers.admin.update_success"
      redirect_to new_admin_category_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.js
    end
  end

  private
  def category_params
    params.require(:category).permit :name, :duration, :word_per_lesson
  end

  def find_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t "controllers.admin.category_not_found"
      redirect_to home_path
    end
  end

  def load_categories
    @categories = Category.sort.paginate page: params[:page],
      per_page: Settings.per_page
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :find_category, only: :show

  def index
    @categories = Category.search(params[:search]).sort
  end

  def show
  end

  private
  def find_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t "controllers.admin.category_not_found"
      redirect_to root_path
    end
  end
end

app/views/categories/_category.html.erb
<tr>
  <td><%= link_to category.name, category_lessons_path(category.id) %></td>
  <td><%= category.duration %></td>
  <td><%= category.word_per_lesson %></td>
</tr>

app/views/categories/_search_form.html.erb
<%= form_tag categories_path, method: :get do %>
  <div class="search-form">
    <%= text_field_tag :search, params[:search], placeholder:
      t(".search_categories"),
        class: "form-control" %>
    <%= submit_tag yield(:button_text), class: "btn btn-primary btn-search" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<% provide :button_text, t("search") %>
<%= render "search_form" %>
<div class="container">
  <table class="table table-striped tbl-categories">
    <thead>
      <tr>
        <th><%= t "name" %></th>
        <th><%= t "duration" %></th>
        <th><%= t "word_per_lesson" %></th>
      </tr>
    </thead>
    <tbody class="list-category">
      <%= render @categories %>
    </tbody>
  </table>
</div>

app/views/categories/show.html.erb
<% provide :title, @category.name %>
<div class="container">
  <div><%= link_to t(".create_lesson"),
    category_lessons_path(params[:id]) %>
  </div>
  <table class="table table-striped tbl-categories">
    <thead>
      <tr>
        <th><%= t "name" %></th>
        <th><%= t "duration" %></th>
        <th><%= t "word_per_lesson" %></th>
      </tr>
    </thead>
    <tbody class="list-category">
      <%= render @category %>
    </tbody>
  </table>
</div>